// Generated by tauri-specta from src-tauri. Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	folioOpen: (path: string) => typedError<FolioInfo, FolioError>(__TAURI_INVOKE("folio_open", { path })),
	folioCreate: (path: string, name: string | null) => typedError<FolioInfo, FolioError>(__TAURI_INVOKE("folio_create", { path, name })),
	folioClose: () => typedError<null, FolioError>(__TAURI_INVOKE("folio_close")),
	folioCurrent: () => typedError<{
	root: string,
	name: string,
	noteCount: number,
} | null, FolioError>(__TAURI_INVOKE("folio_current")),
	folioRecent: () => __TAURI_INVOKE<RecentFolio[]>("folio_recent"),
	folioTree: () => typedError<TreeNode[], FolioError>(__TAURI_INVOKE("folio_tree")),
	noteRead: (path: string) => typedError<NoteContent, FolioError>(__TAURI_INVOKE("note_read", { path })),
	noteWrite: (path: string, text: string, expectedMtime: number | null) => typedError<NoteMeta, FolioError>(__TAURI_INVOKE("note_write", { path, text, expectedMtime })),
	entryCreateNote: (path: string) => typedError<NoteMeta, FolioError>(__TAURI_INVOKE("entry_create_note", { path })),
	entryCreateFolder: (path: string) => typedError<null, FolioError>(__TAURI_INVOKE("entry_create_folder", { path })),
	entryRename: (from: string, to: string) => typedError<null, FolioError>(__TAURI_INVOKE("entry_rename", { from, to })),
	entryTrash: (path: string) => typedError<null, FolioError>(__TAURI_INVOKE("entry_trash", { path })),
	assetWrite: (notePath: string, fileName: string, dataBase64: string) => typedError<AssetInfo, FolioError>(__TAURI_INVOKE("asset_write", { notePath, fileName, dataBase64 })),
	/**  Absolute path of a note-relative asset reference, for `convertFileSrc` in the UI. */
	assetResolve: (notePath: string, target: string) => typedError<string, FolioError>(__TAURI_INVOKE("asset_resolve", { notePath, target })),
	/**  Copies a file chosen in the native dialog into the note's assets folder. */
	assetImport: (notePath: string, source: string) => typedError<AssetInfo, FolioError>(__TAURI_INVOKE("asset_import", { notePath, source })),
	/**  Quick Open's entries: every note's title, aliases and headings, straight from SQLite. */
	folioIndex: () => typedError<NoteIndexEntry[], FolioError>(__TAURI_INVOKE("folio_index")),
	indexStatus: () => typedError<IndexStatus, FolioError>(__TAURI_INVOKE("index_status")),
	/**  Drops the database contents and indexes every note again, on a thread. */
	indexRebuild: () => typedError<null, FolioError>(__TAURI_INVOKE("index_rebuild")),
	/**  Plain full-text search (words, `"phrases"`); the query language lands in WP-2.5. */
	indexSearch: (query: string, limit: number | null) => typedError<SearchHit[], FolioError>(__TAURI_INVOKE("index_search", { query, limit })),
	/**  Resolves each link as seen from `from`; `null` where nothing matches. */
	linkResolve: (from: string, links: LinkQuery[]) => typedError<(string | null)[], FolioError>(__TAURI_INVOKE("link_resolve", { from, links })),
	/**  What renaming `from` → `to` would rewrite. Call before `entry_rename`. */
	linkRenamePreview: (from: string, to: string) => typedError<RenamePreview, FolioError>(__TAURI_INVOKE("link_rename_preview", { from, to })),
	/**  Applies a preview's edits after the rename happened. Returns lines rewritten. */
	linkRenameApply: (notes: NoteEdits[]) => typedError<number, FolioError>(__TAURI_INVOKE("link_rename_apply", { notes })),
	/**  Links in other notes that resolve to `path`. */
	backlinks: (path: string) => typedError<Backlink[], FolioError>(__TAURI_INVOKE("backlinks", { path })),
	/**  Plain-text mentions of the note's name, title or aliases that are not links yet. */
	unlinkedMentions: (path: string) => typedError<Mention[], FolioError>(__TAURI_INVOKE("unlinked_mentions", { path })),
	/**  Turns one mention into a `[[link]]`; false if the line changed meanwhile. */
	linkMentionApply: (source: string, line: number, matched: string, target: string) => typedError<boolean, FolioError>(__TAURI_INVOKE("link_mention_apply", { source, line, matched, target })),
	/**  Every distinct (tag, note) pair in the Folio. */
	tagsList: () => typedError<TagEntry[], FolioError>(__TAURI_INVOKE("tags_list")),
	/**  Paths of the notes carrying `tag` or a tag nested under it. */
	tagNotes: (tag: string) => typedError<string[], FolioError>(__TAURI_INVOKE("tag_notes", { tag })),
	/**  Runs a query in the search language (see `index/search.rs`). */
	searchQuery: (query: string, limit: number | null) => typedError<SearchResponse, FolioError>(__TAURI_INVOKE("search_query", { query, limit })),
	/**
	 *  Returns the words from `words` that the en_AU dictionary (plus the personal and ignore
	 *  lists) does not accept. Tokenising is the editor's job; this only judges words.
	 */
	spellCheck: (words: string[]) => typedError<string[], FolioError>(__TAURI_INVOKE("spell_check", { words })),
	spellSuggest: (word: string) => typedError<string[], FolioError>(__TAURI_INVOKE("spell_suggest", { word })),
	/**  Adds the word to `.aml/dictionary.txt` in the open Folio. */
	spellAdd: (word: string) => typedError<null, FolioError>(__TAURI_INVOKE("spell_add", { word })),
	/**  Ignores the word until the Folio is closed. */
	spellIgnore: (word: string) => typedError<null, FolioError>(__TAURI_INVOKE("spell_ignore", { word })),
	/**  Everything the Sync screen and the status bar show; polled by the UI. */
	syncStatus: () => typedError<SyncStatus, FolioError>(__TAURI_INVOKE("sync_status")),
	/**  Starts the sidecar now and remembers to start it on every launch. */
	syncEnable: () => typedError<SyncStatus, FolioError>(__TAURI_INVOKE("sync_enable")),
	/**  Stops the sidecar and stops auto-starting it. Existing pairing/config is kept. */
	syncDisable: () => typedError<SyncStatus, FolioError>(__TAURI_INVOKE("sync_disable")),
	syncAddDevice: (deviceId: string, name: string, address: string | null) => typedError<SyncStatus, FolioError>(__TAURI_INVOKE("sync_add_device", { deviceId, name, address })),
	syncRemoveDevice: (deviceId: string) => typedError<SyncStatus, FolioError>(__TAURI_INVOKE("sync_remove_device", { deviceId })),
	/**  Accepts a folder the NAS offered, placing it at `path` on this machine. */
	syncAcceptFolder: (folderId: string, label: string, path: string, deviceId: string) => typedError<SyncStatus, FolioError>(__TAURI_INVOKE("sync_accept_folder", { folderId, label, path, deviceId })),
	/**
	 *  Offers a local folder (normally an open Folio) to the NAS. The NAS then has to accept it
	 *  in its own Syncthing UI, choosing where to keep it.
	 */
	syncShareFolder: (path: string, deviceId: string, label: string | null) => typedError<SyncStatus, FolioError>(__TAURI_INVOKE("sync_share_folder", { path, deviceId, label })),
	/**  True when `path` is (inside) a folder the sidecar syncs — used to mark a Folio "Synced". */
	syncIsSyncedPath: (path: string) => typedError<boolean, FolioError>(__TAURI_INVOKE("sync_is_synced_path", { path })),
	syncLogTail: () => typedError<string[], FolioError>(__TAURI_INVOKE("sync_log_tail")),
};

/** Events */
export const events = {
	folioChanged: makeEvent<FolioChanged>("folio-changed"),
	indexProgress: makeEvent<IndexProgress>("index-progress"),
};

/* Types */
/**
 *  Static information about the running app, shown in the About panel and used
 *  by the UI to branch on platform-specific behaviour (shortcut labels etc.).
 */
export type AppInfo = {
	name: string,
	version: string,
	platform: string,
	arch: string,
	debug: boolean,
};

export type AssetInfo = {
	/**  Folio-relative path of the stored file. */
	path: string,
	/**  Path to write into the note (relative to the note's directory, forward slashes). */
	markdownPath: string,
	absolute: string,
	size: number,
};

export type Backlink = {
	source: string,
	sourceTitle: string,
	line: number,
	/**  The whole line, trimmed. */
	context: string,
	/**  Nearest heading above the link, for jumping to the right section. */
	section: string | null,
	kind: string,
};

export type EntryKind = "folder" | "note" | "file";

export type FolioChanged = {
	/**  Folio-relative paths that changed (created, modified, removed or renamed). */
	paths: string[],
};

/**  Errors crossing the IPC boundary. Serialised as a tagged enum so the UI can branch on `kind`. */
export type FolioError = { kind: "noFolioOpen" } | { kind: "notAFolio"; detail: string } | { kind: "notFound"; detail: string } | { kind: "invalidPath"; detail: string } | { kind: "alreadyExists"; detail: string } | { kind: "conflict"; detail: {
	disk_mtime: number,
} } | { kind: "notText"; detail: string } | { kind: "io"; detail: string };

export type FolioInfo = {
	root: string,
	name: string,
	noteCount: number,
};

/**  Emitted while a build or refresh runs; `done == total` marks the end. */
export type IndexProgress = {
	done: number,
	total: number,
};

export type IndexStatus = {
	/**  Notes currently in the index. */
	notes: number,
	building: boolean,
	/**  Progress of the running build, if any. */
	done: number,
	total: number,
	/**  Unix ms of the last completed build or refresh; 0 if never. */
	lastBuilt: number,
	/**  Milliseconds the last build or refresh took. */
	lastDurationMs: number,
};

export type LinkEdit = {
	/**  1-based line. */
	line: number,
	before: string,
	after: string,
};

export type LinkQuery = {
	target: string,
	/**  `wiki`, `embed` or `md`. */
	kind: string,
};

export type Mention = {
	source: string,
	sourceTitle: string,
	line: number,
	context: string,
	/**  The text as it appears in the line (its case may differ from the name). */
	matched: string,
	section: string | null,
};

export type NoteContent = {
	path: string,
	text: string,
	mtime: number,
	size: number,
};

export type NoteEdits = {
	/**  Path before the rename. */
	path: string,
	/**  Path after the rename (differs only for notes inside the renamed entry). */
	newPath: string,
	edits: LinkEdit[],
};

/**  Quick Open's view of a note (ADR-007: fuzzy ranking stays in memory on the UI side). */
export type NoteIndexEntry = {
	path: string,
	/**  Front-matter `title:` if present, else the file name without `.md`. */
	title: string,
	aliases: string[],
	headings: string[],
	mtime: number,
};

export type NoteMeta = {
	path: string,
	mtime: number,
	size: number,
};

export type PendingFolder = {
	id: string,
	label: string,
	offeredBy: string,
	offeredByName: string,
};

export type RecentFolio = {
	path: string,
	name: string,
	lastOpened: number,
};

export type RenamePreview = {
	from: string,
	to: string,
	notes: NoteEdits[],
	/**  Total links that would be rewritten. */
	links: number,
};

export type SearchHit = {
	path: string,
	title: string,
	/**  Matching excerpt with `«»` around the hit terms. */
	snippet: string,
};

export type SearchResponse = {
	results: SearchResult[],
	total: number,
	/**  Set when the query could not be parsed (bad regex, …); results are then empty. */
	error: string | null,
};

export type SearchResult = {
	path: string,
	title: string,
	/**  Matching occurrences of the text terms (0 for field-only queries). */
	matches: number,
	snippets: SearchSnippet[],
};

export type SearchSnippet = {
	line: number,
	/**  The line with matches wrapped in `«»`. */
	text: string,
	section: string | null,
};

export type SyncDevice = {
	id: string,
	name: string,
	connected: boolean,
	address: string,
};

export type SyncFolder = {
	id: string,
	label: string,
	path: string,
	/**  "idle" | "scanning" | "syncing" | "error" | "unknown" … */
	state: string,
	/**  0–100 for this device's copy of the folder. */
	completion: number | null,
	needBytes: number,
	devices: string[],
	error: string | null,
};

export type SyncStatus = {
	enabled: boolean,
	running: boolean,
	myId: string | null,
	version: string | null,
	devices: SyncDevice[],
	folders: SyncFolder[],
	pending: PendingFolder[],
	guiUrl: string,
	error: string | null,
};

/**  One (tag, note) pair; a note appears once per tag however often it uses it. */
export type TagEntry = {
	/**  Lower-case, without `#`, nested with `/`. */
	tag: string,
	path: string,
	title: string,
};

export type TreeNode = {
	name: string,
	/**  Folio-relative path with forward slashes, e.g. `Thesis/chapters/03.md`. */
	path: string,
	kind: EntryKind,
	mtime: number,
	size: number,
	children: TreeNode[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

