// Generated by tauri-specta from src-tauri. Do not edit by hand.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
	folioOpen: (path: string) => typedError<FolioInfo, FolioError>(__TAURI_INVOKE("folio_open", { path })),
	folioCreate: (path: string, name: string | null) => typedError<FolioInfo, FolioError>(__TAURI_INVOKE("folio_create", { path, name })),
	folioClose: () => typedError<null, FolioError>(__TAURI_INVOKE("folio_close")),
	folioCurrent: () => typedError<{
	root: string,
	name: string,
	noteCount: number,
} | null, FolioError>(__TAURI_INVOKE("folio_current")),
	folioRecent: () => __TAURI_INVOKE<RecentFolio[]>("folio_recent"),
	folioTree: () => typedError<TreeNode[], FolioError>(__TAURI_INVOKE("folio_tree")),
	noteRead: (path: string) => typedError<NoteContent, FolioError>(__TAURI_INVOKE("note_read", { path })),
	noteWrite: (path: string, text: string, expectedMtime: number | null) => typedError<NoteMeta, FolioError>(__TAURI_INVOKE("note_write", { path, text, expectedMtime })),
	entryCreateNote: (path: string) => typedError<NoteMeta, FolioError>(__TAURI_INVOKE("entry_create_note", { path })),
	entryCreateFolder: (path: string) => typedError<null, FolioError>(__TAURI_INVOKE("entry_create_folder", { path })),
	entryRename: (from: string, to: string) => typedError<null, FolioError>(__TAURI_INVOKE("entry_rename", { from, to })),
	entryTrash: (path: string) => typedError<null, FolioError>(__TAURI_INVOKE("entry_trash", { path })),
};

/** Events */
export const events = {
	folioChanged: makeEvent<FolioChanged>("folio-changed"),
};

/* Types */
/**
 *  Static information about the running app, shown in the About panel and used
 *  by the UI to branch on platform-specific behaviour (shortcut labels etc.).
 */
export type AppInfo = {
	name: string,
	version: string,
	platform: string,
	arch: string,
	debug: boolean,
};

export type EntryKind = "folder" | "note" | "file";

export type FolioChanged = {
	/**  Folio-relative paths that changed (created, modified, removed or renamed). */
	paths: string[],
};

/**  Errors crossing the IPC boundary. Serialised as a tagged enum so the UI can branch on `kind`. */
export type FolioError = { kind: "noFolioOpen" } | { kind: "notAFolio"; detail: string } | { kind: "notFound"; detail: string } | { kind: "invalidPath"; detail: string } | { kind: "alreadyExists"; detail: string } | { kind: "conflict"; detail: {
	disk_mtime: number,
} } | { kind: "notText"; detail: string } | { kind: "io"; detail: string };

export type FolioInfo = {
	root: string,
	name: string,
	noteCount: number,
};

export type NoteContent = {
	path: string,
	text: string,
	mtime: number,
	size: number,
};

export type NoteMeta = {
	path: string,
	mtime: number,
	size: number,
};

export type RecentFolio = {
	path: string,
	name: string,
	lastOpened: number,
};

export type TreeNode = {
	name: string,
	/**  Folio-relative path with forward slashes, e.g. `Thesis/chapters/03.md`. */
	path: string,
	kind: EntryKind,
	mtime: number,
	size: number,
	children: TreeNode[],
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

