// WP-0.4: computes WCAG contrast for every text/surface pairing in src/app/tokens.css
// and writes docs/qa/contrast-report.md. Fails if a token marked as text falls below 4.5:1.
import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync("src/app/tokens.css", "utf8");

function block(selector) {
  const re = new RegExp(`${selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\{([^}]*)\\}`, "m");
  const m = css.match(re);
  if (!m) throw new Error(`selector not found: ${selector}`);
  const tokens = {};
  for (const line of m[1].split("\n")) {
    const t = line.match(/--(aml-[a-z0-9-]+):\s*(#[0-9a-fA-F]{6})/);
    if (t) tokens[t[1]] = t[2].toLowerCase();
  }
  return tokens;
}

function lum(hex) {
  const c = [1, 3, 5]
    .map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((v) => (v <= 0.03928 ? v / 12.92 : ((v + 0.055) / 1.055) ** 2.4));
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
}
const ratio = (a, b) => {
  const [l1, l2] = [lum(a), lum(b)].sort((x, y) => y - x);
  return (l1 + 0.05) / (l2 + 0.05);
};

// role: "text" must pass 4.5, "large" must pass 3.0, "decorative" is informational only
const PAIRS = [
  ["aml-text", "aml-bg", "text"],
  ["aml-text", "aml-surface", "text"],
  ["aml-primary", "aml-bg", "text"],
  ["aml-primary", "aml-surface", "text"],
  ["aml-text", "aml-highlight", "text"],
  ["aml-accent", "aml-bg", "decorative"],
  ["aml-muted", "aml-bg", "decorative"],
  ["aml-bg", "aml-primary", "text"], // text on primary buttons
];

const modes = { Paper: block(":root"), Ink: block(':root[data-mode="ink"]') };
// Ink inherits anything it doesn't override
for (const k of Object.keys(modes.Paper)) modes.Ink[k] ??= modes.Paper[k];

let failures = 0;
let md =
  "# Contrast report (generated by scripts/contrast-report.mjs)\n\nThresholds: text ≥ 4.5:1 · large ≥ 3:1 · decorative = informational.\n";
for (const [mode, tokens] of Object.entries(modes)) {
  md += `\n## ${mode}\n\n| Foreground | Background | Ratio | Role | Result |\n|---|---|---|---|---|\n`;
  for (const [fg, bg, role] of PAIRS) {
    const r = ratio(tokens[fg], tokens[bg]);
    const need = role === "text" ? 4.5 : role === "large" ? 3 : 0;
    const ok = r >= need;
    if (!ok) failures += 1;
    md += `| \`--${fg}\` ${tokens[fg]} | \`--${bg}\` ${tokens[bg]} | ${r.toFixed(2)} : 1 | ${role} | ${need ? (ok ? "✅" : "❌") : "ℹ️"} |\n`;
  }
}
writeFileSync("docs/qa/contrast-report.md", md);
process.stdout.write(md);
if (failures) {
  process.stderr.write(`\n${failures} contrast failure(s)\n`);
  process.exit(1);
}
