//! AML core. Rust owns all file-system, indexing and sidecar work; the webview
//! only talks to it through the commands collected here (ADR-001).

mod commands;
mod folio;
mod index;
mod sidecar;
mod spell;
mod state;

use tauri_specta::{collect_commands, collect_events, Builder};

/// The single registry of commands and events exposed to the UI.
/// `cargo test` re-exports `src/ipc/bindings.ts` from this (see `tests::export_bindings`).
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app::app_info,
            commands::folio::folio_open,
            commands::folio::folio_create,
            commands::folio::folio_close,
            commands::folio::folio_current,
            commands::folio::folio_recent,
            commands::folio::folio_tree,
            commands::folio::note_read,
            commands::folio::note_write,
            commands::folio::entry_create_note,
            commands::folio::entry_create_folder,
            commands::folio::entry_rename,
            commands::folio::entry_trash,
            commands::folio::asset_write,
            commands::folio::asset_resolve,
            commands::folio::asset_import,
            commands::index::folio_index,
            commands::index::index_status,
            commands::index::index_rebuild,
            commands::index::index_search,
            commands::links::link_resolve,
            commands::links::link_rename_preview,
            commands::links::link_rename_apply,
            commands::spell::spell_check,
            commands::spell::spell_suggest,
            commands::spell::spell_add,
            commands::spell::spell_ignore,
            commands::sync::sync_status,
            commands::sync::sync_enable,
            commands::sync::sync_disable,
            commands::sync::sync_add_device,
            commands::sync::sync_remove_device,
            commands::sync::sync_accept_folder,
            commands::sync::sync_share_folder,
            commands::sync::sync_is_synced_path,
            commands::sync::sync_log_tail,
        ])
        .events(collect_events![
            folio::watch::FolioChanged,
            commands::index::IndexProgress
        ])
}

fn export_bindings(builder: &Builder<tauri::Wry>) {
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// Generated by tauri-specta from src-tauri. Do not edit by hand.\n"),
            "../src/ipc/bindings.ts",
        )
        .expect("failed to export TypeScript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    export_bindings(&builder);

    tauri::Builder::default()
        .manage(state::AppState::default())
        .plugin(tauri_plugin_dialog::init())
        .plugin(
            tauri_plugin_log::Builder::new()
                .level(log::LevelFilter::Info)
                .build(),
        )
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            #[cfg(target_os = "macos")]
            install_mac_menu(app.handle())?;
            log::info!("AML {} starting", env!("CARGO_PKG_VERSION"));
            // The sidecar can take seconds to answer; never block the window from appearing.
            let handle = app.handle().clone();
            std::thread::spawn(move || commands::sync::autostart(&handle));
            Ok(())
        })
        .build(tauri::generate_context!())
        .expect("error while building AML")
        .run(|app, event| {
            if let tauri::RunEvent::Exit = event {
                commands::sync::shutdown(app);
            }
        });
}

/// macOS menu bar without the default "Close Window" (⌘W), which AML uses to close a tab.
/// The Edit menu stays: on macOS, clipboard shortcuts in the webview route through it.
#[cfg(target_os = "macos")]
fn install_mac_menu(app: &tauri::AppHandle) -> tauri::Result<()> {
    use tauri::menu::{MenuBuilder, SubmenuBuilder};
    let app_menu = SubmenuBuilder::new(app, "AML")
        .about(None)
        .separator()
        .services()
        .separator()
        .hide()
        .hide_others()
        .show_all()
        .separator()
        .quit()
        .build()?;
    let edit = SubmenuBuilder::new(app, "Edit")
        .undo()
        .redo()
        .separator()
        .cut()
        .copy()
        .paste()
        .select_all()
        .build()?;
    let window = SubmenuBuilder::new(app, "Window")
        .minimize()
        .maximize()
        .separator()
        .fullscreen()
        .build()?;
    let menu = MenuBuilder::new(app)
        .item(&app_menu)
        .item(&edit)
        .item(&window)
        .build()?;
    app.set_menu(menu)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates the TypeScript bindings. CI fails if this changes a tracked file.
    #[test]
    fn export_bindings_is_current() {
        export_bindings(&specta_builder());
    }
}
