//! AML core. Rust owns all file-system, indexing and sidecar work; the webview
//! only talks to it through the commands collected here (ADR-001).

mod commands;
mod folio;
mod state;

use tauri_specta::{collect_commands, collect_events, Builder};

/// The single registry of commands and events exposed to the UI.
/// `cargo test` re-exports `src/ipc/bindings.ts` from this (see `tests::export_bindings`).
fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::app::app_info,
            commands::folio::folio_open,
            commands::folio::folio_create,
            commands::folio::folio_close,
            commands::folio::folio_current,
            commands::folio::folio_recent,
            commands::folio::folio_tree,
            commands::folio::note_read,
            commands::folio::note_write,
            commands::folio::entry_create_note,
            commands::folio::entry_create_folder,
            commands::folio::entry_rename,
            commands::folio::entry_trash,
        ])
        .events(collect_events![folio::watch::FolioChanged])
}

fn export_bindings(builder: &Builder<tauri::Wry>) {
    builder
        .export(
            specta_typescript::Typescript::default()
                .header("// Generated by tauri-specta from src-tauri. Do not edit by hand.\n"),
            "../src/ipc/bindings.ts",
        )
        .expect("failed to export TypeScript bindings");
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = specta_builder();

    #[cfg(debug_assertions)]
    export_bindings(&builder);

    tauri::Builder::default()
        .manage(state::AppState::default())
        .plugin(tauri_plugin_dialog::init())
        .plugin(
            tauri_plugin_log::Builder::new()
                .level(log::LevelFilter::Info)
                .build(),
        )
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            log::info!("AML {} starting", env!("CARGO_PKG_VERSION"));
            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running AML");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regenerates the TypeScript bindings. CI fails if this changes a tracked file.
    #[test]
    fn export_bindings_is_current() {
        export_bindings(&specta_builder());
    }
}
